const all = {
  products: [
    {
      id: 1,
      title: 'iPhone 9',
      description:
        'An apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple mobile which is nothing like apple',
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      reviews: 899,
      stock: 94,
      brand: 'Apple',
      category: 'smartphones',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/1/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/1/1.jpg',
        'https://cdn.dummyjson.com/product-images/1/2.jpg',
        'https://cdn.dummyjson.com/product-images/1/3.jpg',
        'https://cdn.dummyjson.com/product-images/1/4.jpg',
        'https://cdn.dummyjson.com/product-images/1/thumbnail.jpg',
      ],
    },
    {
      id: 2,
      brand: 'Apple',
      price: 899,
      stock: 34,
      title: 'iPhone X',
      images: [
        'https://i.dummyjson.com/data/products/2/1.jpg',
        'https://i.dummyjson.com/data/products/2/2.jpg',
        'https://i.dummyjson.com/data/products/2/3.jpg',
        'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
      ],
      rating: 4.44,
      reviews: 145,
      category: 'smartphones',
      thumbnail:
        'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
      description:
        'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with a revolutionary Neural Engine Face ID for secure authentication and Apple Pay iOS 12 with Memoji, Screen Time, Siri Shortcuts, and Group FaceTime',
      discountPercentage: 17.94,
    },
    {
      id: 3,
      brand: 'Samsung',
      price: 1249,
      stock: 36,
      title: 'Samsung Universe 9',
      images: [
        'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
      ],
      rating: 4.09,
      reviews: 89,
      category: 'smartphones',
      thumbnail:
        'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
      description:
        "Samsung's new variant which goes beyond Galaxy to the Universe. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with",
      discountPercentage: 15.46,
    },
    {
      id: 4,
      title: 'OPPOF19',
      description:
        'OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021. OPPO F19 is officially announced on April 2021.',
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      reviews: 512,
      stock: 123,
      brand: 'OPPO',
      category: 'smartphones',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/4/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/4/1.jpg',
        'https://cdn.dummyjson.com/product-images/4/2.jpg',
        'https://cdn.dummyjson.com/product-images/4/3.jpg',
        'https://cdn.dummyjson.com/product-images/4/4.jpg',
        'https://cdn.dummyjson.com/product-images/4/thumbnail.jpg',
      ],
    },
    {
      id: 5,
      title: 'Huawei P30',
      description:
        'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      reviews: 256,
      stock: 32,
      brand: 'Huawei',
      category: 'smartphones',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/5/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/5/1.jpg',
        'https://cdn.dummyjson.com/product-images/5/2.jpg',
        'https://cdn.dummyjson.com/product-images/5/3.jpg',
      ],
    },
    {
      id: 6,
      brand: 'Apple',
      price: 1749,
      stock: 83,
      title: 'MacBook Pro',
      images: [
        'https://i.dummyjson.com/data/products/6/1.png',
        'https://i.dummyjson.com/data/products/6/2.jpg',
        'https://i.dummyjson.com/data/products/6/3.png',
        'https://i.dummyjson.com/data/products/6/4.jpg',
      ],
      rating: 4.57,
      reviews: 92,
      category: 'laptops',
      thumbnail:
        'https://i.dummyjson.com/data/products/6/thumbnail.png',
      description:
        'MacBook Pro 2021 with a stunning mini-LED display that may launch between September and November. Experience unparalleled speed and performance with the latest Intel processors and high-capacity SSD storage. The advanced cooling system ensures optimal performance during heavy workloads.',
      discountPercentage: 11.02,
    },
    {
      id: 7,
      title: 'Samsung Galaxy Book',
      description:
        'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched. Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched. Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched. Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched. Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched.',
      price: 1499,
      discountPercentage: 4.15,
      rating: 4.25,
      reviews: 689,
      stock: 50,
      brand: 'Samsung',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/7/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/7/1.jpg',
        'https://cdn.dummyjson.com/product-images/7/2.jpg',
        'https://cdn.dummyjson.com/product-images/7/3.jpg',
        'https://cdn.dummyjson.com/product-images/7/thumbnail.jpg',
      ],
    },
    {
      id: 8,
      title: 'Microsoft Surface Laptop 4',
      description:
        'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen. Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen. Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen. Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',
      price: 1499,
      discountPercentage: 10.23,
      rating: 4.43,
      reviews: 573,
      stock: 68,
      brand: 'Microsoft Surface',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/8/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/8/1.jpg',
        'https://cdn.dummyjson.com/product-images/8/2.jpg',
        'https://cdn.dummyjson.com/product-images/8/3.jpg',
        'https://cdn.dummyjson.com/product-images/8/4.jpg',
        'https://cdn.dummyjson.com/product-images/8/thumbnail.jpg',
      ],
    },
    {
      id: 9,
      brand: 'Infinix',
      price: 1099,
      stock: 96,
      title: 'Infinix INBOOK',
      images: [
        'https://i.dummyjson.com/data/products/9/1.jpg',
        'https://i.dummyjson.com/data/products/9/2.png',
        'https://i.dummyjson.com/data/products/9/3.png',
        'https://i.dummyjson.com/data/products/9/4.jpg',
        'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
      ],
      rating: 4.54,
      reviews: 76,
      category: 'laptops',
      thumbnail:
        'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
      description:
        'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 11.83,
    },
    {
      id: 10,
      title: 'HP Pavilion 15-DK1056WM',
      description:
        "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10. This laptop is a powerhouse for gaming and productivity, featuring the latest technology and high-performance components to ensure a smooth experience. The 10th Gen Core i5 processor, 8GB RAM, and GTX 1650 graphics card deliver exceptional performance, while the 256GB SSD provides fast storage and quick boot times. With Windows 10, you get a secure and user-friendly operating system. Whether you're a gamer or a professional, the HP Pavilion 15-DK1056WM has you covered.",
      price: 1099,
      discountPercentage: 6.18,
      rating: 4.43,
      stock: 89,
      brand: 'HP Pavilion',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg',
      images: [
        'https://cdn.dummyjson.com/product-images/10/1.jpg',
        'https://cdn.dummyjson.com/product-images/10/2.jpg',
        'https://cdn.dummyjson.com/product-images/10/3.jpg',
        'https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg',
      ],
      reviews: 120,
    },
    {
      id: 11,
      title: 'perfume Oil',
      description:
        "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil. Get this exclusive fragrance that captures the essence of Acqua Di Gio by GiorgioArmani. The concentrated attar perfume oil offers a long-lasting and captivating scent. Don't miss the mega discount on this luxurious perfume oil that will make you stand out in any crowd.",
      price: 13,
      discountPercentage: 8.4,
      rating: 4.26,
      stock: 65,
      brand: 'Impression of Acqua Di Gio',
      category: 'fragrances',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/11/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/11/1.jpg',
        'https://cdn.dummyjson.com/product-images/11/2.jpg',
        'https://cdn.dummyjson.com/product-images/11/3.jpg',
        'https://cdn.dummyjson.com/product-images/11/thumbnail.jpg',
      ],
      reviews: 56,
    },
    {
      id: 12,
      brand: 'Royal_Mirage',
      price: 40,
      stock: 52,
      title: 'Brown Perfume',
      images: [
        'https://i.dummyjson.com/data/products/12/1.jpg',
        'https://i.dummyjson.com/data/products/12/2.jpg',
        'https://i.dummyjson.com/data/products/12/3.png',
        'https://i.dummyjson.com/data/products/12/4.jpg',
        'https://i.dummyjson.com/data/products/12/thumbnail.jpg',
      ],
      rating: 4,
      reviews: 107,
      category: 'fragrances',
      thumbnail:
        'https://i.dummyjson.com/data/products/12/thumbnail.jpg',
      description:
        'Royal_Mirage Sport Brown Perfume for Men & Women - 120ml. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 15.66,
    },
    {
      id: 13,
      title: 'Fog Scent Xpressio Perfume',
      description:
        "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men. Enjoy the refreshing and long-lasting scent of Fog Scent Xpressio Perfume. This perfume is specially crafted for men, providing a cool and captivating fragrance that lasts all day. With a 100ml capacity, it's perfect for everyday use. Experience the best of men's perfumery with Fog Scent Xpressio.",
      price: 13,
      discountPercentage: 8.14,
      rating: 4.59,
      stock: 61,
      brand: 'Fog Scent Xpressio',
      category: 'fragrances',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/13/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/13/1.jpg',
        'https://cdn.dummyjson.com/product-images/13/2.png',
        'https://cdn.dummyjson.com/product-images/13/3.jpg',
        'https://cdn.dummyjson.com/product-images/13/4.jpg',
        'https://cdn.dummyjson.com/product-images/13/thumbnail.webp',
      ],
      reviews: 89,
    },
    {
      id: 14,
      title: 'Non-Alcoholic Concentrated Perfume Oil',
      description:
        "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil. Experience the original Al Munakh® by Mahal Al Musk, our impression of Climate. This non-alcoholic concentrated perfume oil offers a unique and long-lasting fragrance that sets you apart. With a 6ml capacity, it's easy to carry and perfect for any occasion.",
      price: 120,
      discountPercentage: 15.6,
      rating: 4.21,
      stock: 114,
      brand: 'Al Munakh',
      category: 'fragrances',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/14/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/14/1.jpg',
        'https://cdn.dummyjson.com/product-images/14/2.jpg',
        'https://cdn.dummyjson.com/product-images/14/3.jpg',
        'https://cdn.dummyjson.com/product-images/14/thumbnail.jpg',
      ],
      reviews: 76,
    },
    {
      id: 15,
      title: 'Eau De Perfume Spray',
      description:
        'Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality. Indulge in the genuine Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen. This high-quality Eau De Perfume Spray offers a luxurious and authentic fragrance experience. With a rating of 4.7, it ensures a premium and long-lasting scent. Elevate your presence with the captivating aroma of Lord - Al-Rehab.',
      price: 30,
      discountPercentage: 10.99,
      rating: 4.7,
      stock: 105,
      brand: 'Lord - Al-Rehab',
      category: 'fragrances',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/15/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/15/1.jpg',
        'https://cdn.dummyjson.com/product-images/15/2.jpg',
        'https://cdn.dummyjson.com/product-images/15/3.jpg',
        'https://cdn.dummyjson.com/product-images/15/4.jpg',
        'https://cdn.dummyjson.com/product-images/15/thumbnail.jpg',
      ],
      reviews: 105,
    },
    {
      id: 16,
      title: 'Hyaluronic Acid Serum',
      description:
        "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid. Achieve radiant and plump skin with L'OrÃ©al Paris Hyaluron Expert Replumping Serum. Formulated with 1.5% Hyaluronic Acid, this serum provides intense hydration, helping to replump and revitalize your skin. Experience the power of hyaluronic acid for a more youthful and radiant complexion.",
      price: 19,
      discountPercentage: 13.31,
      rating: 4.83,
      stock: 110,
      brand: "L'Oreal Paris",
      category: 'skincare',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/16/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/16/1.png',
        'https://cdn.dummyjson.com/product-images/16/2.webp',
        'https://cdn.dummyjson.com/product-images/16/3.jpg',
        'https://cdn.dummyjson.com/product-images/16/4.jpg',
        'https://cdn.dummyjson.com/product-images/16/thumbnail.jpg',
      ],
      reviews: 92,
    },
    {
      id: 17,
      title: 'Tree Oil 30ml',
      description:
        'Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria. Experience the natural benefits of Hemani Tea Tree Oil 30ml. Tea tree oil is known for its antibacterial properties and is a versatile solution for various skin concerns. Add this essential oil to your skincare routine for a healthier and clearer complexion.',
      price: 12,
      discountPercentage: 4.09,
      rating: 4.52,
      stock: 78,
      brand: 'Hemani Tea',
      category: 'skincare',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/17/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/17/1.jpg',
        'https://cdn.dummyjson.com/product-images/17/2.jpg',
        'https://cdn.dummyjson.com/product-images/17/3.jpg',
        'https://cdn.dummyjson.com/product-images/17/thumbnail.jpg',
      ],
      reviews: 43,
    },
    {
      id: 18,
      title: 'Oil Free Moisturizer 100ml',
      description:
        'Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen. Keep your skin hydrated and protected with Dermive Oil-Free Moisturizer 100ml. This moisturizer is specially formulated with ceramides, hyaluronic acid, and sunscreen (SPF 20) to provide your skin with the essential hydration and protection it needs. Enjoy a lightweight and non-greasy formula for a comfortable all-day feel.',
      price: 40,
      discountPercentage: 13.1,
      rating: 4.56,
      stock: 88,
      brand: 'Dermive',
      category: 'skincare',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/18/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/18/1.jpg',
        'https://cdn.dummyjson.com/product-images/18/2.jpg',
        'https://cdn.dummyjson.com/product-images/18/3.jpg',
        'https://cdn.dummyjson.com/product-images/18/4.jpg',
        'https://cdn.dummyjson.com/product-images/18/thumbnail.jpg',
      ],
      reviews: 65,
    },
    {
      id: 19,
      title: 'Skin Beauty Serum.',
      description:
        "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m. Enhance your skin's beauty with ROREC Collagen Hyaluronic Acid White Face Serum. This serum is designed to promote a radiant and youthful complexion, thanks to the benefits of collagen and hyaluronic acid. With a net weight of 15ml, it offers a concentrated formula for effective results.",
      price: 46,
      discountPercentage: 10.68,
      rating: 4.42,
      stock: 54,
      brand: 'ROREC White Rice',
      category: 'skincare',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/19/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/19/1.jpg',
        'https://cdn.dummyjson.com/product-images/19/2.jpg',
        'https://cdn.dummyjson.com/product-images/19/3.png',
        'https://cdn.dummyjson.com/product-images/19/thumbnail.jpg',
      ],
      reviews: 78,
    },
    {
      id: 20,
      title: 'Freckle Treatment Cream- 15gm',
      description:
        "Fair & Clear is Pakistan's only pure Freckle cream which helps fade Freckles, Dark spots and pigments. Mercury level is 0%, so there are no side effects. Achieve clear and flawless skin with Fair & Clear Freckle Treatment Cream. This cream is specially formulated to target freckles, dark spots, and pigments. With a mercury-free formula, it ensures effective results without any side effects.",
      price: 70,
      discountPercentage: 16.99,
      rating: 4.06,
      stock: 140,
      brand: 'Fair & Clear',
      category: 'skincare',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/20/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/20/1.jpg',
        'https://cdn.dummyjson.com/product-images/20/2.jpg',
        'https://cdn.dummyjson.com/product-images/20/3.jpg',
        'https://cdn.dummyjson.com/product-images/20/4.jpg',
        'https://cdn.dummyjson.com/product-images/20/thumbnail.jpg',
      ],
      reviews: 109,
    },
    {
      id: 21,
      title: '- Daal Masoor 500 grams',
      description:
        'Fine quality Branded Product Keep in a cool and dry place. Enjoy the finest quality Daal Masoor with Saaf & Khaas. Each pack contains 500 grams of premium daal masoor that is perfect for a variety of dishes. Keep it in a cool and dry place to preserve its fine quality. Saaf & Khaas brings you the best for your kitchen.',
      price: 20,
      discountPercentage: 4.81,
      rating: 4.44,
      stock: 133,
      brand: 'Saaf & Khaas',
      category: 'groceries',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/21/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/product-images/21/1.png',
        'https://cdn.dummyjson.com/product-images/21/2.jpg',
        'https://cdn.dummyjson.com/product-images/21/3.jpg',
      ],
      reviews: 67,
    },
    {
      id: 22,
      title: 'Elbow Macaroni - 400 gm',
      description:
        'Product details of Bake Parlor Big Elbow Macaroni - 400 gm. Indulge in delicious pasta dishes with Bake Parlor Big Elbow Macaroni. Each pack contains 400 grams of high-quality elbow macaroni, perfect for your favorite pasta recipes. Enjoy the authentic taste and texture that Bake Parlor Big brings to your table.',
      price: 14,
      discountPercentage: 15.58,
      rating: 4.57,
      stock: 146,
      brand: 'Bake Parlor Big',
      category: 'groceries',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/22/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/22/1.jpg',
        'https://cdn.dummyjson.com/product-images/22/2.jpg',
        'https://cdn.dummyjson.com/product-images/22/3.jpg',
      ],
      reviews: 89,
    },
    {
      id: 23,
      title: 'Orange Essence Food Flavour',
      description:
        'Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item. Add a burst of flavor to your culinary creations with Orange Essence Food Flavour. Ideal for cakes and baking, this food flavor enhances the taste of your favorite treats. Elevate your cooking and baking experience with the delightful aroma and taste of orange essence.',
      price: 14,
      discountPercentage: 8.04,
      rating: 4.85,
      stock: 26,
      brand: 'Baking Food Items',
      category: 'groceries',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/23/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/23/1.jpg',
        'https://cdn.dummyjson.com/product-images/23/2.jpg',
        'https://cdn.dummyjson.com/product-images/23/3.jpg',
        'https://cdn.dummyjson.com/product-images/23/4.jpg',
        'https://cdn.dummyjson.com/product-images/23/thumbnail.jpg',
      ],
      reviews: 34,
    },
    {
      id: 24,
      title: 'Cereals Muesli Fruit Nuts',
      description:
        'Original Fauji Cereal Muesli 250gm box pack. Original Fauji Cereals Muesli Fruit Nuts Flakes Breakfast Cereal. Start your day right with Fauji Cereals Muesli. Each 250gm box pack contains a delightful blend of fruits, nuts, and flakes for a wholesome breakfast. Enjoy the original taste of Fauji cereals for a nutritious and tasty start to your morning.',
      price: 46,
      discountPercentage: 16.8,
      rating: 4.94,
      stock: 113,
      brand: 'Fauji',
      category: 'groceries',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/24/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/24/1.jpg',
        'https://cdn.dummyjson.com/product-images/24/2.jpg',
        'https://cdn.dummyjson.com/product-images/24/3.jpg',
        'https://cdn.dummyjson.com/product-images/24/4.jpg',
        'https://cdn.dummyjson.com/product-images/24/thumbnail.jpg',
      ],
      reviews: 112,
    },
    {
      id: 25,
      title: 'Gulab Powder 50 Gram',
      description:
        'Dry Rose Flower Powder Gulab Powder 50 Gram. Treats Wounds. Experience the natural benefits of Gulab Powder with Dry Rose. This 50-gram pack of Gulab Powder is perfect for various applications, including treating wounds. Enjoy the healing properties and pleasant fragrance of rose flower powder from Dry Rose.',
      price: 70,
      discountPercentage: 13.58,
      rating: 4.87,
      stock: 47,
      brand: 'Dry Rose',
      category: 'groceries',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/25/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/25/1.png',
        'https://cdn.dummyjson.com/product-images/25/2.jpg',
        'https://cdn.dummyjson.com/product-images/25/3.png',
        'https://cdn.dummyjson.com/product-images/25/4.jpg',
        'https://cdn.dummyjson.com/product-images/25/thumbnail.jpg',
      ],
      reviews: 56,
    },
    {
      id: 26,
      title: 'Plant Hanger For Home',
      description:
        'Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf. Add a touch of boho chic to your home with the Boho Decor Plant Hanger. This wall decoration features a macrame wall hanging shelf for your favorite plants. Elevate your home decor with this stylish and functional plant hanger from Boho Decor.',
      price: 41,
      discountPercentage: 17.86,
      rating: 4.08,
      stock: 131,
      brand: 'Boho Decor',
      category: 'home-decoration',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/26/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/26/1.jpg',
        'https://cdn.dummyjson.com/product-images/26/2.jpg',
        'https://cdn.dummyjson.com/product-images/26/3.jpg',
        'https://cdn.dummyjson.com/product-images/26/4.jpg',
        'https://cdn.dummyjson.com/product-images/26/5.jpg',
        'https://cdn.dummyjson.com/product-images/26/thumbnail.jpg',
      ],
      reviews: 42,
    },
    {
      id: 27,
      title: 'Flying Wooden Bird',
      description:
        'Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm. Bring a touch of nature into your home with the Flying Wooden Bird. This package includes 6 3D-shaped wooden birds with adhesive tape for easy installation. Made from wooden MDF and laminated for durability, these birds add a whimsical and artistic element to your home decor.',
      price: 51,
      discountPercentage: 15.58,
      rating: 4.41,
      stock: 17,
      brand: 'Flying Wooden',
      category: 'home-decoration',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/27/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/27/1.jpg',
        'https://cdn.dummyjson.com/product-images/27/2.jpg',
        'https://cdn.dummyjson.com/product-images/27/3.jpg',
        'https://cdn.dummyjson.com/product-images/27/4.jpg',
        'https://cdn.dummyjson.com/product-images/27/thumbnail.webp',
      ],
      reviews: 23,
    },
    {
      id: 28,
      title: '3D Embellishment Art Lamp',
      description:
        '3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included). Illuminate your space with the 3D Embellishment Art Lamp. This LED lamp features a 3D wall art design with a convenient on/off button. It is cell-operated, with batteries included for easy setup. Add a touch of artistic lighting to your room with this unique and stylish lamp.',
      price: 20,
      discountPercentage: 16.49,
      rating: 4.82,
      stock: 54,
      brand: 'LED Lights',
      category: 'home-decoration',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/28/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/28/1.jpg',
        'https://cdn.dummyjson.com/product-images/28/2.jpg',
        'https://cdn.dummyjson.com/product-images/28/3.png',
        'https://cdn.dummyjson.com/product-images/28/4.jpg',
        'https://cdn.dummyjson.com/product-images/28/thumbnail.jpg',
      ],
      reviews: 76,
    },
    {
      id: 29,
      title: 'Handcraft Chinese Style',
      description:
        'Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate. Elevate your home decor with the Handcraft Chinese Style art. This luxury ceramic vase comes with a brass fruit plate, perfect for adding a touch of elegance to your home. Ideal for palace, hotel, villa, and mansion settings, this handcrafted piece is a statement of sophistication.',
      price: 60,
      discountPercentage: 15.34,
      rating: 4.44,
      stock: 7,
      brand: 'Luxury Palace',
      category: 'home-decoration',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/29/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/29/1.jpg',
        'https://cdn.dummyjson.com/product-images/29/2.jpg',
        'https://cdn.dummyjson.com/product-images/29/3.webp',
        'https://cdn.dummyjson.com/product-images/29/4.webp',
        'https://cdn.dummyjson.com/product-images/29/thumbnail.webp',
      ],
      reviews: 10,
    },
    {
      id: 30,
      title: 'Key Holder',
      description:
        'Attractive Design Metallic material Four key hooks Reliable & Durable Premium Quality. Keep your keys organized with the Attractive Design Key Holder. Made from metallic material, this key holder features four key hooks for your convenience. It is reliable, durable, and offers premium quality for your peace of mind. Keep your space tidy and your keys easily accessible with this stylish key holder.',
      price: 30,
      discountPercentage: 2.92,
      rating: 4.92,
      stock: 54,
      brand: 'Golden',
      category: 'home-decoration',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/30/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/30/1.jpg',
        'https://cdn.dummyjson.com/product-images/30/2.jpg',
        'https://cdn.dummyjson.com/product-images/30/3.jpg',
        'https://cdn.dummyjson.com/product-images/30/thumbnail.jpg',
      ],
      reviews: 32,
    },
    {
      id: 31,
      title: 'Mornadi Velvet Bed',
      description:
        'Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set. Upgrade your bedroom with the Mornadi Velvet Bed. This bed features a velvet bed base with a headboard and slats support. The classic style adds a touch of sophistication to your bedroom furniture. Experience comfort and style with the Mornadi Velvet Bed Set.',
      price: 40,
      discountPercentage: 17,
      rating: 4.16,
      stock: 140,
      brand: 'Furniture Bed Set',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/31/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/31/1.jpg',
        'https://cdn.dummyjson.com/product-images/31/2.jpg',
        'https://cdn.dummyjson.com/product-images/31/3.jpg',
        'https://cdn.dummyjson.com/product-images/31/4.jpg',
        'https://cdn.dummyjson.com/product-images/31/thumbnail.jpg',
      ],
      reviews: 54,
    },
    {
      id: 32,
      title: 'Sofa for Coffee Cafe',
      description:
        "Rattan Outdoor Furniture Set Waterproof Rattan Sofa for Coffee Cafe. This beautiful sofa is made of high-quality rattan, designed to withstand various weather conditions. It's perfect for your coffee cafe, providing both style and comfort. The waterproof feature ensures durability, making it suitable for both indoor and outdoor use. The elegant design adds a touch of sophistication to your cafe ambiance.",
      price: 50,
      discountPercentage: 15.59,
      rating: 4.74,
      stock: 30,
      brand: 'Rattan Outdoor',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/32/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/32/1.jpg',
        'https://cdn.dummyjson.com/product-images/32/2.jpg',
        'https://cdn.dummyjson.com/product-images/32/3.jpg',
        'https://cdn.dummyjson.com/product-images/32/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 33,
      title: '3 Tier Corner Shelves',
      description:
        '3 Tier Corner Shelves - A set of three wall-mounted kitchen shelves perfect for your coffee cafe. These floating bedroom shelves not only provide storage but also add a modern touch to your space. The sturdy construction ensures durability, and the wall-mount design saves floor space. Ideal for displaying kitchen essentials or decorative items.',
      price: 700,
      discountPercentage: 17,
      rating: 4.31,
      stock: 106,
      brand: 'Kitchen Shelf',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/33/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/33/1.jpg',
        'https://cdn.dummyjson.com/product-images/33/2.jpg',
        'https://cdn.dummyjson.com/product-images/33/3.jpg',
        'https://cdn.dummyjson.com/product-images/33/4.jpg',
        'https://cdn.dummyjson.com/product-images/33/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 34,
      brand: 'Multi Purpose',
      price: 50,
      stock: 136,
      title: 'Plastic Table',
      images: [
        'https://i.dummyjson.com/data/products/34/1.jpg',
        'https://i.dummyjson.com/data/products/34/2.jpg',
        'https://i.dummyjson.com/data/products/34/3.jpg',
        'https://i.dummyjson.com/data/products/34/4.jpg',
        'https://i.dummyjson.com/data/products/34/thumbnail.jpg',
      ],
      rating: 4.01,
      reviews: 112,
      category: 'furniture',
      thumbnail:
        'https://i.dummyjson.com/data/products/34/thumbnail.jpg',
      description:
        'V﻿ery good quality plastic table for multi-purpose now in reasonable price. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 4,
    },
    {
      id: 35,
      title: '3 DOOR PORTABLE',
      description:
        'Material: Stainless Steel and Fabric. Item Size: 110 cm x 45 cm x 175 cm. Package Contents: 1 Storage Wardrobe. This portable wardrobe provides a convenient storage solution for your clothes. Made of high-quality stainless steel and fabric, it offers durability and a stylish design. The spacious interior allows for organized storage, and the three doors enhance accessibility.',
      price: 41,
      discountPercentage: 7.98,
      rating: 4.06,
      stock: 68,
      brand: 'AmnaMart',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/35/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/35/1.jpg',
        'https://cdn.dummyjson.com/product-images/35/2.jpg',
        'https://cdn.dummyjson.com/product-images/35/3.jpg',
        'https://cdn.dummyjson.com/product-images/35/4.jpg',
        'https://cdn.dummyjson.com/product-images/35/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 36,
      title: 'Sleeve Shirt Womens',
      description:
        'Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized. Elevate your professional wardrobe with this sleeve shirt for women. Made of high-quality cotton, it offers comfort and style. The solid color adds versatility, making it suitable for various occasions. Ideal for work blouses and wholesale clothing.',
      price: 90,
      discountPercentage: 10.89,
      rating: 4.26,
      stock: 39,
      brand: 'Professional Wear',
      category: 'tops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/36/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/36/1.jpg',
        'https://cdn.dummyjson.com/product-images/36/2.webp',
        'https://cdn.dummyjson.com/product-images/36/3.webp',
        'https://cdn.dummyjson.com/product-images/36/4.jpg',
        'https://cdn.dummyjson.com/product-images/36/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 37,
      title: 'Tank Tops for Womens/Girls',
      description:
        "Pack of 3 camisoles, very comfortable soft cotton stuff, comfortable in all four seasons. Stay comfortable in every season with this pack of 3 camisoles. The soft cotton fabric ensures a pleasant feel on your skin. Versatile for various occasions, these tank tops are a must-have in every women's or girl's wardrobe.",
      price: 50,
      discountPercentage: 12.05,
      rating: 4.52,
      stock: 107,
      brand: 'Soft Cotton',
      category: 'tops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/37/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/37/1.jpg',
        'https://cdn.dummyjson.com/product-images/37/2.jpg',
        'https://cdn.dummyjson.com/product-images/37/3.jpg',
        'https://cdn.dummyjson.com/product-images/37/4.jpg',
        'https://cdn.dummyjson.com/product-images/37/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 38,
      title: 'Sublimation Plain Kids Tank',
      description:
        'Sublimation plain kids tank tops wholesale. Dress your kids in style with these sublimation plain tank tops. Ideal for casual wear or as a blank canvas for customization. The wholesale pricing makes it an affordable choice for parents looking for quality clothing for their kids.',
      price: 100,
      discountPercentage: 11.12,
      rating: 4.8,
      stock: 20,
      brand: 'Soft Cotton',
      category: 'tops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/38/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/38/1.png',
        'https://cdn.dummyjson.com/product-images/38/2.jpg',
        'https://cdn.dummyjson.com/product-images/38/3.jpg',
        'https://cdn.dummyjson.com/product-images/38/4.jpg',
      ],
      reviews: 74,
    },
    {
      id: 39,
      title: 'Women Sweaters Wool',
      description:
        "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater. Stay warm and stylish with this custom winter fall zebra knit crop top. Made of high-quality wool and mohair, this sweater offers both comfort and a fashionable look. Perfect for the colder seasons, it adds a touch of coziness to your wardrobe.",
      price: 600,
      discountPercentage: 17.2,
      rating: 4.55,
      stock: 55,
      brand: 'Top Sweater',
      category: 'tops',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/39/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/39/1.jpg',
        'https://cdn.dummyjson.com/product-images/39/2.jpg',
        'https://cdn.dummyjson.com/product-images/39/3.jpg',
        'https://cdn.dummyjson.com/product-images/39/4.jpg',
        'https://cdn.dummyjson.com/product-images/39/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 40,
      brand: 'Top Sweater',
      price: 57,
      stock: 84,
      title: 'women winter clothes',
      images: [
        'https://i.dummyjson.com/data/products/40/1.jpg',
        'https://i.dummyjson.com/data/products/40/2.jpg',
      ],
      rating: 4.91,
      reviews: 124,
      category: 'tops',
      thumbnail:
        'https://i.dummyjson.com/data/products/40/thumbnail.jpg',
      description:
        'women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 13.39,
    },
    {
      id: 41,
      title: 'NIGHT SUIT',
      description:
        "NIGHT SUIT RED MICKY MOUSE for Girls. Fantastic suits for a comfortable night's sleep. Make bedtime fun with this adorable red Mickey Mouse night suit. Designed for girls, these suits provide both comfort and style for a good night's sleep. The cute Mickey Mouse prints add a playful touch.",
      price: 55,
      discountPercentage: 15.05,
      rating: 4.65,
      stock: 21,
      brand: 'RED MICKY MOUSE',
      category: 'womens-dresses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/41/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/41/1.jpg',
        'https://cdn.dummyjson.com/product-images/41/2.webp',
        'https://cdn.dummyjson.com/product-images/41/3.jpg',
        'https://cdn.dummyjson.com/product-images/41/4.jpg',
        'https://cdn.dummyjson.com/product-images/41/thumbnail.webp',
      ],
      reviews: 74,
    },
    {
      id: 47,
      brand: 'Synthetic Leather',
      price: 120,
      stock: 50,
      title: 'Sneaker shoes',
      images: [
        'https://i.dummyjson.com/data/products/47/1.jpg',
        'https://i.dummyjson.com/data/products/47/2.jpg',
        'https://i.dummyjson.com/data/products/47/3.jpg',
        'https://i.dummyjson.com/data/products/47/thumbnail.jpeg',
      ],
      rating: 4.19,
      reviews: 78,
      category: 'womens-shoes',
      thumbnail:
        'https://i.dummyjson.com/data/products/47/thumbnail.jpeg',
      description:
        'Synthetic Leather Casual Sneaker shoes for Women/Girls. Sneakers For Women. Elevate your shoe collection with these stylish and comfortable sneakers. The synthetic leather ensures durability and style.',
      discountPercentage: 10.37,
    },
    {
      id: 43,
      title: 'Frock Gold Printed',
      description:
        'Ghazi Fabric long frock gold printed ready-to-wear stitched collection (G992). Elevate your wardrobe with this gold printed frock from Ghazi Fabric. The long, ready-to-wear design (G992) offers a stylish and convenient option for various occasions. The gold print adds a touch of luxury, making it a standout piece in your collection.',
      price: 600,
      discountPercentage: 15.55,
      rating: 4.31,
      stock: 150,
      brand: 'Ghazi Fabric',
      category: 'womens-dresses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/43/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/43/1.jpg',
        'https://cdn.dummyjson.com/product-images/43/2.jpg',
        'https://cdn.dummyjson.com/product-images/43/3.jpg',
        'https://cdn.dummyjson.com/product-images/43/4.jpg',
        'https://cdn.dummyjson.com/product-images/43/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 44,
      title: 'Ladies Multicolored Dress',
      description:
        "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears. Make a fashion statement with this ladies' multicolored dress. The classy shirt design is perfect for everyday wear and adds a touch of elegance to semi-casual occasions. Stand out in style with this versatile and chic dress.",
      price: 79,
      discountPercentage: 16.88,
      rating: 4.03,
      stock: 2,
      brand: 'Ghazi Fabric',
      category: 'womens-dresses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/44/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/44/1.jpg',
        'https://cdn.dummyjson.com/product-images/44/2.jpg',
        'https://cdn.dummyjson.com/product-images/44/3.jpg',
        'https://cdn.dummyjson.com/product-images/44/4.jpg',
        'https://cdn.dummyjson.com/product-images/44/thumbnail.jpg',
      ],
      reviews: 74,
    },
    {
      id: 45,
      title: 'Malai Maxi Dress',
      description:
        'Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff',
      price: 50,
      discountPercentage: 5.07,
      rating: 4.67,
      stock: 96,
      brand: 'IELGY',
      category: 'womens-dresses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/45/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/45/1.jpg',
        'https://cdn.dummyjson.com/product-images/45/2.webp',
        'https://cdn.dummyjson.com/product-images/45/3.jpg',
        'https://cdn.dummyjson.com/product-images/45/4.jpg',
        'https://cdn.dummyjson.com/product-images/45/thumbnail.jpg',
      ],
      reviews: 56,
    },
    {
      id: 46,
      title: "Women's Shoes",
      description:
        'Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber',
      price: 40,
      discountPercentage: 16.96,
      rating: 4.14,
      stock: 72,
      brand: 'IELGY fashion',
      category: 'womens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/46/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/46/1.webp',
        'https://cdn.dummyjson.com/product-images/46/2.jpg',
        'https://cdn.dummyjson.com/product-images/46/3.jpg',
        'https://cdn.dummyjson.com/product-images/46/4.jpg',
        'https://cdn.dummyjson.com/product-images/46/thumbnail.jpg',
      ],
      reviews: 99,
    },
    {
      id: 47,
      title: 'Sneaker Shoes',
      description:
        'Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women',
      price: 120,
      discountPercentage: 10.37,
      rating: 4.19,
      stock: 50,
      brand: 'Synthetic Leather',
      category: 'womens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg',
      images: [
        'https://cdn.dummyjson.com/product-images/47/1.jpg',
        'https://cdn.dummyjson.com/product-images/47/2.jpg',
        'https://cdn.dummyjson.com/product-images/47/3.jpg',
        'https://cdn.dummyjson.com/product-images/47/thumbnail.jpeg',
      ],
      reviews: 78,
    },
    {
      id: 48,
      title: 'Women Strip Heel',
      description:
        'Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped',
      price: 40,
      discountPercentage: 10.83,
      rating: 4.02,
      stock: 25,
      brand: 'Sandals Flip Flops',
      category: 'womens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/48/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/48/1.jpg',
        'https://cdn.dummyjson.com/product-images/48/2.jpg',
        'https://cdn.dummyjson.com/product-images/48/3.jpg',
        'https://cdn.dummyjson.com/product-images/48/4.jpg',
        'https://cdn.dummyjson.com/product-images/48/thumbnail.jpg',
      ],
      reviews: 64,
    },
    {
      id: 49,
      title: 'Chappals & Shoe Ladies Metallic',
      description:
        'Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals',
      price: 23,
      discountPercentage: 2.62,
      rating: 4.72,
      stock: 107,
      brand: 'Maasai Sandals',
      category: 'womens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/49/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/49/1.jpg',
        'https://cdn.dummyjson.com/product-images/49/2.jpg',
        'https://cdn.dummyjson.com/product-images/49/3.webp',
        'https://cdn.dummyjson.com/product-images/49/thumbnail.jpg',
      ],
      reviews: 86,
    },
    {
      id: 50,
      title: 'Women Shoes',
      description:
        '2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes',
      price: 36,
      discountPercentage: 16.87,
      rating: 4.33,
      stock: 46,
      brand: 'Arrivals Genuine',
      category: 'womens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/50/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/50/1.jpeg',
        'https://cdn.dummyjson.com/product-images/50/2.jpg',
        'https://cdn.dummyjson.com/product-images/50/3.jpg',
      ],
      reviews: 72,
    },
    {
      id: 51,
      title: 'Half Sleeves T Shirts',
      description:
        'Many stores are creating new designs and trends every month and every year. Daraz.pk has a beautiful range of men fashion brands',
      price: 23,
      discountPercentage: 12.76,
      rating: 4.26,
      stock: 132,
      brand: 'Vintage Apparel',
      category: 'mens-shirts',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/51/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/51/1.png',
        'https://cdn.dummyjson.com/product-images/51/2.jpg',
        'https://cdn.dummyjson.com/product-images/51/3.jpg',
        'https://cdn.dummyjson.com/product-images/51/thumbnail.jpg',
      ],
      reviews: 56,
    },
    {
      id: 52,
      brand: 'FREE FIRE',
      price: 10,
      stock: 128,
      title: 'FREE FIRE T Shirt',
      images: [
        'https://i.dummyjson.com/data/products/52/1.png',
        'https://i.dummyjson.com/data/products/52/2.png',
        'https://i.dummyjson.com/data/products/52/3.jpg',
        'https://i.dummyjson.com/data/products/52/4.jpg',
        'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
      ],
      rating: 4.52,
      reviews: 82,
      category: 'mens-shirts',
      thumbnail:
        'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
      description:
        "High-quality and professionally printed FREE FIRE T Shirt. It doesn't just look high quality; it is high quality. Express your gaming style with this unique and comfortable T-shirt.",
      discountPercentage: 14.72,
    },
    {
      id: 53,
      title: 'Printed High Quality T Shirts',
      description: 'Brand: Vintage Apparel, Export quality',
      price: 35,
      discountPercentage: 7.54,
      rating: 4.89,
      stock: 6,
      brand: 'Vintage Apparel',
      category: 'mens-shirts',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/53/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/53/1.webp',
        'https://cdn.dummyjson.com/product-images/53/2.jpg',
        'https://cdn.dummyjson.com/product-images/53/3.jpg',
        'https://cdn.dummyjson.com/product-images/53/4.jpg',
        'https://cdn.dummyjson.com/product-images/53/thumbnail.jpg',
      ],
      reviews: 78,
    },
    {
      id: 54,
      title: 'PUBG Printed Graphic T-Shirt',
      description:
        'Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking',
      price: 46,
      discountPercentage: 16.44,
      rating: 4.62,
      stock: 136,
      brand: 'The Warehouse',
      category: 'mens-shirts',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/54/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/54/1.jpg',
        'https://cdn.dummyjson.com/product-images/54/2.jpg',
        'https://cdn.dummyjson.com/product-images/54/3.jpg',
        'https://cdn.dummyjson.com/product-images/54/4.jpg',
        'https://cdn.dummyjson.com/product-images/54/thumbnail.jpg',
      ],
      reviews: 64,
    },
    {
      id: 55,
      title: 'Money Heist Printed Summer T-Shirts',
      description:
        'Fabric Jercy, Size: M & L Wear Stylish Dual Stitched',
      price: 66,
      discountPercentage: 15.97,
      rating: 4.9,
      stock: 122,
      brand: 'The Warehouse',
      category: 'mens-shirts',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/55/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/55/1.jpg',
        'https://cdn.dummyjson.com/product-images/55/2.webp',
        'https://cdn.dummyjson.com/product-images/55/3.jpg',
        'https://cdn.dummyjson.com/product-images/55/4.jpg',
        'https://cdn.dummyjson.com/product-images/55/thumbnail.jpg',
      ],
      reviews: 86,
    },
    {
      id: 56,
      brand: 'Sneakers',
      price: 40,
      stock: 6,
      title: 'Sneakers Joggers Shoes',
      images: [
        'https://i.dummyjson.com/data/products/56/1.jpg',
        'https://i.dummyjson.com/data/products/56/2.jpg',
        'https://i.dummyjson.com/data/products/56/3.jpg',
        'https://i.dummyjson.com/data/products/56/4.jpg',
        'https://i.dummyjson.com/data/products/56/5.jpg',
        'https://i.dummyjson.com/data/products/56/thumbnail.jpg',
      ],
      rating: 4.38,
      reviews: 117,
      category: 'mens-shoes',
      thumbnail:
        'https://i.dummyjson.com/data/products/56/thumbnail.jpg',
      description:
        'Gender: Men, Colors: Same as Displayed. Condition: 100% Brand New. These stylish Sneakers Joggers Shoes are designed for comfort and fashion. Elevate your casual look with these high-quality shoes.',
      discountPercentage: 12.57,
    },
    {
      id: 57,
      title: 'Loafers for Men',
      description:
        "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccasins - Pure Nylon (Rubber) Export Quality. Step out in style with these men's loafers. Made from high-quality rubber and nylon, these shoes offer both comfort and durability. The stylish design makes them suitable for various occasions.",
      price: 47,
      discountPercentage: 10.91,
      rating: 4.91,
      stock: 20,
      brand: 'Rubber',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/57/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/57/1.jpg',
        'https://cdn.dummyjson.com/product-images/57/2.jpg',
        'https://cdn.dummyjson.com/product-images/57/3.jpg',
        'https://cdn.dummyjson.com/product-images/57/4.jpg',
        'https://cdn.dummyjson.com/product-images/57/thumbnail.jpg',
      ],
      reviews: 95,
    },
    {
      id: 58,
      title: 'Formal Offices Shoes',
      description:
        'Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe, Outsole Material: Rubber. Elevate your formal look with these solid-patterned formal shoes. Made from high-quality PU, they feature a pointed toe and a rubber outsole for comfort and style. Ideal for office wear and formal occasions.',
      price: 57,
      discountPercentage: 12,
      rating: 4.41,
      stock: 68,
      brand: 'The Warehouse',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/58/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/58/1.jpg',
        'https://cdn.dummyjson.com/product-images/58/2.jpg',
        'https://cdn.dummyjson.com/product-images/58/3.jpg',
        'https://cdn.dummyjson.com/product-images/58/4.jpg',
        'https://cdn.dummyjson.com/product-images/58/thumbnail.jpg',
      ],
      reviews: 73,
    },
    {
      id: 59,
      title: 'Spring and Summer Shoes',
      description:
        'Comfortable stretch cloth, lightweight body; rubber sole, anti-skid wear. Step into the spring and summer seasons with these comfortable and lightweight shoes. The stretch cloth provides a snug fit, and the rubber sole ensures anti-skid wear. Perfect for casual and outdoor activities.',
      price: 20,
      discountPercentage: 8.71,
      rating: 4.33,
      stock: 137,
      brand: 'Sneakers',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/59/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/59/1.jpg',
        'https://cdn.dummyjson.com/product-images/59/2.jpg',
        'https://cdn.dummyjson.com/product-images/59/3.jpg',
        'https://cdn.dummyjson.com/product-images/59/4.jpg',
        'https://cdn.dummyjson.com/product-images/59/thumbnail.jpg',
      ],
      reviews: 60,
    },
    {
      id: 60,
      title: 'Stylish Casual Jeans Shoes',
      description:
        'High Quality, Stylish design, Comfortable wear, Fashion, Durable. Step out in style with these high-quality and stylish casual jeans shoes. Designed for comfort and durability, these shoes are perfect for a fashionable and casual look. A must-have for your footwear collection.',
      price: 58,
      discountPercentage: 7.55,
      rating: 4.55,
      stock: 129,
      brand: 'Sneakers',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/60/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/60/1.jpg',
        'https://cdn.dummyjson.com/product-images/60/2.jpg',
        'https://cdn.dummyjson.com/product-images/60/3.jpg',
        'https://cdn.dummyjson.com/product-images/60/thumbnail.jpg',
      ],
      reviews: 42,
    },
    {
      id: 61,
      title: 'Leather Straps Wristwatch',
      description:
        'Style: Sport, Clasp: Buckles, Water Resistance Depth: 3Bar. Enhance your sporty look with this stylish leather straps wristwatch. Featuring a sporty design, buckles clasp, and water resistance up to 3Bar, this watch is both functional and fashionable. A perfect accessory for your active lifestyle.',
      price: 120,
      discountPercentage: 7.14,
      rating: 4.63,
      stock: 91,
      brand: 'Naviforce',
      category: 'mens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/61/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/61/1.jpg',
        'https://cdn.dummyjson.com/product-images/61/2.png',
        'https://cdn.dummyjson.com/product-images/61/3.jpg',
      ],
      reviews: 88,
    },
    {
      id: 62,
      title: 'Waterproof Leather Brand Watch',
      description:
        'Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours. Stay on time and on trend with this waterproof leather brand watch. Featuring a crown with environmental IPS bronze electroplating and a display system of 12 hours, this watch combines style and functionality.',
      price: 46,
      discountPercentage: 3.15,
      rating: 4.05,
      stock: 95,
      brand: 'SKMEI 9117',
      category: 'mens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/62/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/62/1.jpg',
        'https://cdn.dummyjson.com/product-images/62/2.jpg',
      ],
      reviews: 76,
    },
    {
      id: 63,
      title: 'Royal Blue Premium Watch',
      description:
        'Men Silver Chain Royal Blue Premium Watch Latest Analog Watch. Make a statement with this royal blue premium watch. Designed with a silver chain and the latest analog watch technology, this timepiece adds a touch of sophistication to your overall look.',
      price: 50,
      discountPercentage: 2.56,
      rating: 4.89,
      stock: 142,
      brand: 'SKMEI 9117',
      category: 'mens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/63/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/63/1.jpg',
        'https://cdn.dummyjson.com/product-images/63/2.jpg',
        'https://cdn.dummyjson.com/product-images/63/3.png',
        'https://cdn.dummyjson.com/product-images/63/4.jpeg',
      ],
      reviews: 105,
    },
    {
      id: 64,
      brand: 'Strap Skeleton',
      price: 46,
      stock: 61,
      title: 'Leather Strap Skeleton Watch',
      images: [
        'https://i.dummyjson.com/data/products/64/1.jpg',
        'https://i.dummyjson.com/data/products/64/2.webp',
        'https://i.dummyjson.com/data/products/64/3.jpg',
        'https://i.dummyjson.com/data/products/64/thumbnail.jpg',
      ],
      rating: 4.98,
      reviews: 104,
      category: 'mens-watches',
      thumbnail:
        'https://i.dummyjson.com/data/products/64/thumbnail.jpg',
      description:
        'Luxurious Leather Strap Skeleton Watch for Men with a stylish and latest design. Make a bold fashion statement with this elegant timepiece. Perfect for formal and casual occasions.',
      discountPercentage: 10.2,
    },
    {
      id: 65,
      title: 'Stainless Steel Wrist Watch',
      description:
        "Elegance meets style in this extraordinary Stainless Steel Wrist Watch for men. Unbox sophistication with this classy timepiece, crafted with precision and packed in a luxurious box. This watch is not just an accessory; it's a statement of your refined taste.",
      price: 47,
      discountPercentage: 17.79,
      rating: 4.79,
      stock: 94,
      brand: 'Stainless',
      category: 'mens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/65/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/65/1.jpg',
        'https://cdn.dummyjson.com/product-images/65/2.webp',
        'https://cdn.dummyjson.com/product-images/65/3.jpg',
        'https://cdn.dummyjson.com/product-images/65/4.webp',
        'https://cdn.dummyjson.com/product-images/65/thumbnail.webp',
      ],
      reviews: 88,
    },
    {
      id: 66,
      title: 'Steel Analog Couple Watches',
      description:
        'Experience the epitome of elegance with these Steel Analog Couple Watches. The unique, trendy, and comfortable design makes these watches a must-have for couples who appreciate distinctive fashion. Elevate your style with this chic and fashionable timepiece.',
      price: 35,
      discountPercentage: 3.23,
      rating: 4.79,
      stock: 24,
      brand: 'Eastern Watches',
      category: 'womens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/66/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/66/1.jpg',
        'https://cdn.dummyjson.com/product-images/66/2.jpg',
        'https://cdn.dummyjson.com/product-images/66/3.jpg',
        'https://cdn.dummyjson.com/product-images/66/4.JPG',
        'https://cdn.dummyjson.com/product-images/66/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 67,
      title: 'Fashion Magnetic Wrist Watch',
      description:
        'Indulge in awesomeness with this top-selling Fashion Magnetic Wrist Watch. Unveil the originality and unbeatable affordability of this company-manufactured product. The magnetic strap adds a modern touch to your wrist, making it a must-have for the trendsetter in you.',
      price: 60,
      discountPercentage: 16.69,
      rating: 4.03,
      stock: 46,
      brand: 'Eastern Watches',
      category: 'womens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/67/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/67/1.jpg',
        'https://cdn.dummyjson.com/product-images/67/2.jpg',
        'https://cdn.dummyjson.com/product-images/67/3.jpg',
        'https://cdn.dummyjson.com/product-images/67/4.jpg',
        'https://cdn.dummyjson.com/product-images/67/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 68,
      brand: 'Luxury Digital',
      price: 57,
      stock: 77,
      title: 'Stylish Luxury Digital Watch',
      images: [
        'https://i.dummyjson.com/data/products/68/1.jpg',
        'https://i.dummyjson.com/data/products/68/2.jpg',
      ],
      rating: 4.55,
      reviews: 96,
      category: 'womens-watches',
      thumbnail:
        'https://i.dummyjson.com/data/products/68/thumbnail.webp',
      description:
        'Stylish Luxury Digital Watch For Girls/Women - LED Smart Ladies Watches For Girls. Enhance your style with this fashionable and functional accessory. Stay on trend with the latest in smartwatch technology.',
      discountPercentage: 9.03,
    },
    {
      id: 69,
      title: 'Golden Watch Pearls Bracelet Watch',
      description:
        'Discover the elegance of the Golden Watch Pearls Bracelet Watch designed exclusively for girls. This Golden Chain Ladies Bracelet Watch for Women is a detailed and sophisticated timepiece that complements your style. Add a touch of glamour to your wrist with this exquisite watch.',
      price: 47,
      discountPercentage: 17.55,
      rating: 4.77,
      stock: 89,
      brand: 'Watch Pearls',
      category: 'womens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/69/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/69/1.jpg',
        'https://cdn.dummyjson.com/product-images/69/2.jpg',
        'https://cdn.dummyjson.com/product-images/69/3.webp',
        'https://cdn.dummyjson.com/product-images/69/4.jpg',
        'https://cdn.dummyjson.com/product-images/69/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 70,
      title: 'Stainless Steel Women',
      description:
        'Step into the world of fashion with the Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch. This Lady Bracelet Watch with Quartz movement is a perfect accessory for ladies who appreciate timeless elegance. Elevate your style with this chic and sophisticated timepiece from the Bracelet brand.',
      price: 35,
      discountPercentage: 8.98,
      rating: 4.08,
      stock: 111,
      brand: 'Bracelet',
      category: 'womens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/70/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/70/1.jpg',
        'https://cdn.dummyjson.com/product-images/70/2.jpg',
        'https://cdn.dummyjson.com/product-images/70/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 71,
      title: 'Women Shoulder Bags',
      description:
        'Introducing the LouisWill Women Shoulder Bags with Long Clutches, Cross Body Bags, Phone Bags, PU Leather Hand Bags, Large Capacity Card Holders, Zipper Coin Purses, and Fashion Crossbody Bags for Girls and Ladies. This versatile and stylish bag is a must-have for every fashion-forward woman.',
      price: 46,
      discountPercentage: 14.65,
      rating: 4.71,
      stock: 17,
      brand: 'LouisWill',
      category: 'womens-bags',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/71/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/71/1.jpg',
        'https://cdn.dummyjson.com/product-images/71/2.jpg',
        'https://cdn.dummyjson.com/product-images/71/3.webp',
        'https://cdn.dummyjson.com/product-images/71/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 72,
      brand: 'LouisWill',
      price: 23,
      stock: 27,
      title: 'Handbag For Girls',
      images: [
        'https://i.dummyjson.com/data/products/72/1.jpg',
        'https://i.dummyjson.com/data/products/72/2.png',
        'https://i.dummyjson.com/data/products/72/3.webp',
        'https://i.dummyjson.com/data/products/72/4.jpg',
        'https://i.dummyjson.com/data/products/72/thumbnail.webp',
      ],
      rating: 4.91,
      reviews: 88,
      category: 'womens-bags',
      thumbnail:
        'https://i.dummyjson.com/data/products/72/thumbnail.webp',
      description:
        'This fashion-forward handbag is designed to add a charming effect to your casual outfit. Made of high-quality synthetic leather, this bag is both stylish and durable. Elevate your accessory game with this trendy handbag.',
      discountPercentage: 17.5,
    },
    {
      id: 73,
      title: 'Fancy Hand Clutch',
      description:
        'Add a charming effect to your casual outfit with this Fancy Hand Clutch. Made of synthetic leather, this fashion accessory from the Bracelet brand is designed for those who seek style and functionality. Elevate your look with this trendy and versatile hand clutch.',
      price: 44,
      discountPercentage: 10.39,
      rating: 4.18,
      stock: 101,
      brand: 'Bracelet',
      category: 'womens-bags',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/73/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/73/1.jpg',
        'https://cdn.dummyjson.com/product-images/73/2.webp',
        'https://cdn.dummyjson.com/product-images/73/3.jpg',
        'https://cdn.dummyjson.com/product-images/73/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 74,
      title: 'Leather Hand Bag',
      description:
        'Featuring an attractive design, this Leather Hand Bag is a must-have accessory in your collection. We offer different kinds of bags for boys, kids, women, girls, and also unisex options. Elevate your style with this fashionable and functional bag from Copenhagen Luxe.',
      price: 57,
      discountPercentage: 11.19,
      rating: 4.01,
      stock: 43,
      brand: 'Copenhagen Luxe',
      category: 'womens-bags',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/74/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/74/1.jpg',
        'https://cdn.dummyjson.com/product-images/74/2.jpg',
        'https://cdn.dummyjson.com/product-images/74/3.jpg',
        'https://cdn.dummyjson.com/product-images/74/4.jpg',
        'https://cdn.dummyjson.com/product-images/74/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 75,
      title: 'Seven Pocket Women Bag',
      description:
        "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag. This stylish and spacious handbag is perfect for carrying all your essentials. With seven pockets, it offers ample space to keep your belongings organized. The adjustable strap allows you to wear it as a shoulder bag or crossbody bag. Made with high-quality materials, this bag is durable and fashionable. The golden steal frame adds a touch of elegance. Stay organized and stylish with this seven-pocket women's bag.",
      price: 68,
      discountPercentage: 14.87,
      rating: 4.93,
      stock: 13,
      brand: 'Steal Frame',
      category: 'womens-bags',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/75/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/75/1.jpg',
        'https://cdn.dummyjson.com/product-images/75/2.jpg',
        'https://cdn.dummyjson.com/product-images/75/3.jpg',
        'https://cdn.dummyjson.com/product-images/75/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 76,
      title: 'Silver Ring Set Women',
      description:
        'Jewelry Type: Rings. Certificate Type: None. Plating: Silver Plated. Shape/Pattern: None. Style: CLASSIC Religious. Enhance your style with this elegant silver ring set for women. The set includes beautifully crafted rings with intricate details. The silver plating adds a touch of sophistication, making it suitable for various occasions. Whether you wear them individually or as a set, these rings will complement your look. The classic and religious design makes them a timeless addition to your jewelry collection.',
      price: 70,
      discountPercentage: 13.57,
      rating: 4.61,
      stock: 51,
      brand: 'Darojay',
      category: 'womens-jewellery',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/76/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/76/1.jpg',
        'https://cdn.dummyjson.com/product-images/76/2.jpg',
        'https://cdn.dummyjson.com/product-images/76/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 77,
      title: 'Rose Ring',
      description:
        'Brand: The Greetings. Flower Colour: Red. Ring Colour: Golden. Size: Adjustable. Add a touch of romance to your style with this beautiful rose ring. The golden color and adjustable size make it a versatile accessory for various outfits. The red flower detail adds a pop of color, making it perfect for special occasions or everyday wear. The Greetings brand ensures high quality, and the elegant design of this rose ring will make it a cherished piece in your jewellery collection.',
      price: 100,
      discountPercentage: 3.22,
      rating: 4.21,
      stock: 149,
      brand: 'Copenhagen Luxe',
      category: 'womens-jewellery',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/77/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/77/1.jpg',
        'https://cdn.dummyjson.com/product-images/77/2.jpg',
        'https://cdn.dummyjson.com/product-images/77/3.jpg',
        'https://cdn.dummyjson.com/product-images/77/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 78,
      title: 'Rhinestone Korean Style Open Rings',
      description:
        'Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women. Elevate your style with these fashionable open rings. The set includes three adjustable rings with pearl and rhinestone details. The Korean style design adds a trendy and chic element to your jewellery collection. Perfect for women who appreciate unique and stylish accessories. These rings are versatile and can be worn on various occasions, adding a touch of glamour to your overall look.',
      price: 30,
      discountPercentage: 8.02,
      rating: 4.69,
      stock: 9,
      brand: 'Fashion Jewellery',
      category: 'womens-jewellery',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/78/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/78/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 79,
      title: 'Elegant Female Pearl Earrings',
      description:
        'Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set. Complete your party look with this elegant set of pearl earrings. The set includes nine pairs of earrings with zircon and pearl details. These earrings are perfect for special occasions and add a touch of sophistication to your outfit. The high-quality materials ensure durability, making them suitable for regular wear. Enhance your jewellery collection with these stylish and versatile pearl earrings.',
      price: 30,
      discountPercentage: 12.8,
      rating: 4.74,
      stock: 16,
      brand: 'Fashion Jewellery',
      category: 'womens-jewellery',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/79/thumbnail.jpg',
      images: ['https://cdn.dummyjson.com/product-images/79/1.jpg'],
      reviews: 88,
    },
    {
      id: 80,
      title: 'Chain Pin Tassel Earrings',
      description:
        'Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product). Elevate your style with these unique chain pin tassel earrings. The silver color and butterfly design make them a standout accessory. The long chain adds a trendy and fashionable element to your look. Made with high-quality materials, these earrings are durable and long-lasting. Enhance your jewellery collection with this pair of ear cuff butterfly earrings for a touch of glamour.',
      price: 45,
      discountPercentage: 17.75,
      rating: 4.59,
      stock: 9,
      brand: 'Cuff Butterfly',
      category: 'womens-jewellery',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/80/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/80/1.jpg',
        'https://cdn.dummyjson.com/product-images/80/2.jpg',
        'https://cdn.dummyjson.com/product-images/80/3.png',
        'https://cdn.dummyjson.com/product-images/80/4.jpg',
        'https://cdn.dummyjson.com/product-images/80/thumbnail.jpg',
      ],
      reviews: 88,
    },
    {
      id: 81,
      title: 'Round Silver Frame Sun Glasses',
      description:
        "A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings. Stay stylish and protected with these round silver frame sunglasses. The sleek design and silver frame add a touch of elegance to your look. Whether you're driving, on vacation, or enjoying outdoor activities, these sunglasses are a must-have accessory. Box packed for added convenience and protection.",
      price: 19,
      discountPercentage: 10.1,
      rating: 4.94,
      stock: 78,
      brand: 'Designer Sun Glasses',
      category: 'sunglasses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/81/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/81/1.jpg',
        'https://cdn.dummyjson.com/product-images/81/2.jpg',
        'https://cdn.dummyjson.com/product-images/81/3.jpg',
        'https://cdn.dummyjson.com/product-images/81/4.webp',
        'https://cdn.dummyjson.com/product-images/81/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 82,
      brand: 'Designer Sun Glasses',
      price: 50,
      stock: 78,
      title: 'Kabir Singh Square Sunglass',
      images: [
        'https://i.dummyjson.com/data/products/82/1.jpg',
        'https://i.dummyjson.com/data/products/82/2.webp',
        'https://i.dummyjson.com/data/products/82/3.jpg',
        'https://i.dummyjson.com/data/products/82/4.jpg',
        'https://i.dummyjson.com/data/products/82/thumbnail.jpg',
      ],
      rating: 4.62,
      reviews: 110,
      category: 'sunglasses',
      thumbnail:
        'https://i.dummyjson.com/data/products/82/thumbnail.jpg',
      description:
        'Original Metal Kabir Singh design 2020 Sunglasses for Men. Brand Designer Sun Glasses Kabir Singh Square Sunglass. Elevate your style with these trendy and stylish sunglasses. Protect your eyes with fashion-forward eyewear.',
      discountPercentage: 15.6,
    },
    {
      id: 83,
      title: 'Wiley X Night Vision Yellow Glasses',
      description:
        'Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches. Enhance your riding experience with these Wiley X night vision yellow glasses. Designed for riders, these glasses offer anti-fog protection and shield your eyes from dust and viruses. The set includes a free night glass cover for added convenience. Stay safe and stylish with Wiley X.',
      price: 30,
      discountPercentage: 6.33,
      rating: 4.97,
      stock: 115,
      brand: 'mastar watch',
      category: 'sunglasses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/83/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/83/1.jpg',
        'https://cdn.dummyjson.com/product-images/83/2.jpg',
        'https://cdn.dummyjson.com/product-images/83/3.jpg',
        'https://cdn.dummyjson.com/product-images/83/4.jpg',
        'https://cdn.dummyjson.com/product-images/83/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 84,
      title: 'Square Sunglasses',
      description:
        'Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059. Stay fashionable with these oversized square sunglasses. The retro gradient big frame adds a touch of glamour to your look. Designed for women, these sunglasses are a stylish accessory for any occasion. The one-piece gafas shade with a clear lens ensures a chic and trendy appearance. Elevate your style with these square sunglasses.',
      price: 28,
      discountPercentage: 13.89,
      rating: 4.64,
      stock: 64,
      brand: 'mastar watch',
      category: 'sunglasses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/84/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/84/1.jpg',
        'https://cdn.dummyjson.com/product-images/84/2.jpg',
        'https://cdn.dummyjson.com/product-images/84/thumbnail.jpg',
      ],
      reviews: 388,
    },
    {
      id: 85,
      title: 'LouisWill Men Sunglasses',
      description:
        'LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers. Protect your eyes with these LouisWill men sunglasses. The polarized lenses and UV400 protection ensure safety while driving or enjoying outdoor activities. The day-night dual-use feature adds versatility to these stylish sunglasses. The AL-MG frame provides durability, and the free box offers convenient storage for drivers on the go.',
      price: 50,
      discountPercentage: 11.27,
      rating: 4.98,
      stock: 92,
      brand: 'LouisWill',
      category: 'sunglasses',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/85/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/85/1.jpg',
        'https://cdn.dummyjson.com/product-images/85/2.jpg',
        'https://cdn.dummyjson.com/product-images/85/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 86,
      title: 'Bluetooth Aux',
      description:
        'Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3. Upgrade your car audio experience with this Bluetooth car aux transmitter. The universal 3.5mm streaming adapter allows you to enjoy hands-free music and calls. The aux audio receiver is compatible with phones and MP3 players, providing a convenient and wireless solution for your car audio needs. Stay connected and entertained on the go.',
      price: 25,
      discountPercentage: 10.56,
      rating: 4.57,
      stock: 22,
      brand: 'Car Aux',
      category: 'automotive',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/86/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/86/1.jpg',
        'https://cdn.dummyjson.com/product-images/86/2.webp',
        'https://cdn.dummyjson.com/product-images/86/3.jpg',
        'https://cdn.dummyjson.com/product-images/86/4.jpg',
        'https://cdn.dummyjson.com/product-images/86/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 87,
      title: 't Temperature Controller Incubator Controller',
      description:
        'Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1. Achieve precise temperature control with the W1209 DC12V temperature controller. Suitable for both heating and cooling purposes, this controller has a temperature control range of -50 to +110 degrees. The high measurement accuracy of 0.1 and control accuracy of 0.1 make it ideal for various applications. Ensure optimal conditions with this reliable temperature controller.',
      price: 40,
      discountPercentage: 11.3,
      rating: 4.54,
      stock: 37,
      brand: 'W1209 DC12V',
      category: 'automotive',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/87/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/87/1.jpg',
        'https://cdn.dummyjson.com/product-images/87/2.jpg',
        'https://cdn.dummyjson.com/product-images/87/3.jpg',
        'https://cdn.dummyjson.com/product-images/87/4.jpg',
        'https://cdn.dummyjson.com/product-images/87/thumbnail.jpg',
      ],
      reviews: 388,
    },
    {
      id: 88,
      title: 'TC Reusable Silicone Magic Washing Gloves',
      description:
        'TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose. Make cleaning a breeze with these TC Reusable Silicone Magic Washing Gloves. The built-in scrubber and cleaning brush make it easy to clean kitchen dishes, vegetables, fruits, and more. The heat-resistant pair is perfect for various cleaning tasks, including bathroom, car wash, and pet care. A versatile and convenient solution for all your cleaning needs.',
      price: 29,
      discountPercentage: 3.19,
      rating: 4.98,
      stock: 42,
      brand: 'TC Reusable',
      category: 'automotive',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/88/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/88/1.jpg',
        'https://cdn.dummyjson.com/product-images/88/2.jpg',
        'https://cdn.dummyjson.com/product-images/88/3.jpg',
        'https://cdn.dummyjson.com/product-images/88/4.webp',
        'https://cdn.dummyjson.com/product-images/88/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 89,
      brand: 'TC Reusable',
      price: 40,
      stock: 79,
      title: 'Qualcomm original Car Charger',
      images: [
        'https://i.dummyjson.com/data/products/89/1.jpg',
        'https://i.dummyjson.com/data/products/89/2.jpg',
        'https://i.dummyjson.com/data/products/89/3.jpg',
        'https://i.dummyjson.com/data/products/89/4.jpg',
        'https://i.dummyjson.com/data/products/89/thumbnail.jpg',
      ],
      rating: 4.2,
      reviews: 98,
      category: 'automotive',
      thumbnail:
        'https://i.dummyjson.com/data/products/89/thumbnail.jpg',
      description:
        'best Quality Charger , Highly Recommended to all best Quality Charger , Highly Recommended to all. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 17.53,
    },
    {
      id: 90,
      title: 'Cycle Bike Glow',
      description:
        'Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motorcycles and cars. Bright led will turn on when the wheel rotates, creating a unique and attention-grabbing effect. Enhance your bike or motorcycle with this Neon LED Light cycle bike glow. The universal fitment and easy installation make it suitable for various vehicles. The bright LED lights turn on when the wheel rotates, adding a cool and unique touch to your ride.',
      price: 35,
      discountPercentage: 11.08,
      rating: 4.1,
      stock: 63,
      brand: 'Neon LED Light',
      category: 'automotive',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/90/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/90/1.jpg',
        'https://cdn.dummyjson.com/product-images/90/2.jpg',
        'https://cdn.dummyjson.com/product-images/90/3.jpg',
        'https://cdn.dummyjson.com/product-images/90/4.jpg',
        'https://cdn.dummyjson.com/product-images/90/thumbnail.jpg',
      ],
      reviews: 388,
    },
    {
      id: 91,
      title: 'Black Motorbike',
      description:
        'Engine Type: Wet sump, Single Cylinder, Four Stroke, Two Valves, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke: 47.0 x 49.5 MM. Experience the thrill of the open road with the METRO 70cc Motorcycle - MR70. This black motorbike features a powerful engine with wet sump, single cylinder, and four-stroke technology. The air-cooled system with SOHC chain drive ensures a smooth and reliable ride. With a sleek design and advanced features, this motorcycle is perfect for riders seeking adventure and style.',
      price: 569,
      discountPercentage: 13.63,
      rating: 4.04,
      stock: 115,
      brand: 'METRO 70cc Motorcycle - MR70',
      category: 'motorcycle',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/91/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/91/1.jpg',
        'https://cdn.dummyjson.com/product-images/91/2.jpg',
        'https://cdn.dummyjson.com/product-images/91/3.jpg',
        'https://cdn.dummyjson.com/product-images/91/4.jpg',
        'https://cdn.dummyjson.com/product-images/91/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 92,
      title: 'HOT SALE IN EUROPE electric racing motorcycle',
      description:
        'HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles. Embrace the future of transportation with the HOT SALE IN EUROPE electric racing motorcycle. This cutting-edge electric motorcycle is a hot seller in Europe, offering a thrilling and eco-friendly riding experience. Perfect for adults, this electric motorcycle combines style and performance. Join the revolution of electric mobility with the BRAVE BULL electric racing motorcycle.',
      price: 920,
      discountPercentage: 14.4,
      rating: 4.19,
      stock: 22,
      brand: 'BRAVE BULL',
      category: 'motorcycle',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/92/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/92/1.jpg',
        'https://cdn.dummyjson.com/product-images/92/2.jpg',
        'https://cdn.dummyjson.com/product-images/92/3.jpg',
        'https://cdn.dummyjson.com/product-images/92/4.jpg',
      ],
      reviews: 757,
    },
    {
      id: 93,
      brand: 'shock absorber',
      price: 1050,
      stock: 127,
      title: 'Automatic Motor Gas Motorcycles',
      images: [
        'https://i.dummyjson.com/data/products/93/1.jpg',
        'https://i.dummyjson.com/data/products/93/2.jpg',
        'https://i.dummyjson.com/data/products/93/3.jpg',
        'https://i.dummyjson.com/data/products/93/4.jpg',
        'https://i.dummyjson.com/data/products/93/thumbnail.jpg',
      ],
      rating: 4.84,
      reviews: 95,
      category: 'motorcycle',
      thumbnail:
        'https://i.dummyjson.com/data/products/93/thumbnail.jpg',
      description:
        '150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 3.34,
    },
    {
      id: 94,
      title: 'new arrivals Fashion motocross goggles',
      description:
        "new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle. Stay stylish and protected with the new arrivals Fashion motocross goggles. Whether you're into motocross or just want a fashionable accessory, these goggles are a perfect choice. Designed for motorcycle enthusiasts, these motocross goggles add a touch of flair to your riding gear. The sleek and modern design makes them a must-have for any rider. Elevate your style with JIEPOLLY's new arrivals in motocross fashion.",
      price: 900,
      discountPercentage: 3.85,
      rating: 4.06,
      stock: 109,
      brand: 'JIEPOLLY',
      category: 'motorcycle',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/94/thumbnail.webp',
      images: [
        'https://cdn.dummyjson.com/product-images/94/1.webp',
        'https://cdn.dummyjson.com/product-images/94/2.jpg',
        'https://cdn.dummyjson.com/product-images/94/3.jpg',
        'https://cdn.dummyjson.com/product-images/94/thumbnail.webp',
      ],
      reviews: 757,
    },
    {
      id: 95,
      title: 'Wholesale cargo lashing Belt',
      description:
        "Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle. Secure your cargo with the Wholesale cargo lashing Belt. This tie-down end ratchet strap is a customized strap with a 25mm width, designed for motorcycles up to 1500kgs. The rubber handle provides a comfortable grip, making it easy to secure your cargo. Whether you're transporting motorcycles or other items, trust Xiangle for high-quality cargo straps.",
      price: 930,
      discountPercentage: 17.67,
      rating: 4.21,
      stock: 144,
      brand: 'Xiangle',
      category: 'motorcycle',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/95/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/95/1.jpg',
        'https://cdn.dummyjson.com/product-images/95/2.jpg',
        'https://cdn.dummyjson.com/product-images/95/3.jpg',
        'https://cdn.dummyjson.com/product-images/95/4.jpg',
        'https://cdn.dummyjson.com/product-images/95/thumbnail.jpg',
      ],
      reviews: 388,
    },
    {
      id: 96,
      title: 'lighting ceiling kitchen',
      description:
        "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern. Illuminate your kitchen with the lighting brilliance of this ceiling pendant light. Perfect for both decorative and functional purposes, this slim hanging chandelier adds a modern touch to your kitchen. With a discount percentage of 14.89%, it's an affordable and stylish lighting solution. Stock up on these lighting fixtures from lightingbrilliance and transform your kitchen into a well-lit and stylish space.",
      price: 30,
      discountPercentage: 14.89,
      rating: 4.83,
      stock: 96,
      brand: 'lightingbrilliance',
      category: 'lighting',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/96/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/96/1.jpg',
        'https://cdn.dummyjson.com/product-images/96/2.jpg',
        'https://cdn.dummyjson.com/product-images/96/3.jpg',
        'https://cdn.dummyjson.com/product-images/96/4.jpg',
        'https://cdn.dummyjson.com/product-images/96/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 97,
      title: 'Metal Ceramic Flower',
      description:
        "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp. Add a touch of vintage elegance to your home with the Metal Ceramic Flower Chandelier from Ifei Home. This American vintage hanging pendant lamp features a unique design with metal and ceramic flowers. With a discount percentage of 10.94%, it's both stylish and affordable. Illuminate your living space with this eye-catching piece and enjoy the warm glow it brings to your home.",
      price: 35,
      discountPercentage: 10.94,
      rating: 4.93,
      stock: 146,
      brand: 'Ifei Home',
      category: 'lighting',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/97/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/97/1.jpg',
        'https://cdn.dummyjson.com/product-images/97/2.jpg',
        'https://cdn.dummyjson.com/product-images/97/3.jpg',
        'https://cdn.dummyjson.com/product-images/97/4.webp',
        'https://cdn.dummyjson.com/product-images/97/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 98,
      title: '3 lights lndenpant kitchen islang',
      description:
        "3 lights lndenpant kitchen islang dining room pendant rice paper chandelier contemporary led pendant light modern chandelier. Upgrade your kitchen lighting with the DADAWU 3 Lights Pendant. This contemporary LED pendant light features a stylish design, perfect for illuminating your kitchen island or dining area. With a discount percentage of 5.92%, it's an excellent choice for those seeking modern and energy-efficient lighting solutions. Stock up on this DADAWU pendant for a sophisticated and well-lit kitchen.",
      price: 34,
      discountPercentage: 5.92,
      rating: 4.99,
      stock: 44,
      brand: 'DADAWU',
      category: 'lighting',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/98/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/98/1.jpg',
        'https://cdn.dummyjson.com/product-images/98/2.jpg',
        'https://cdn.dummyjson.com/product-images/98/3.jpg',
        'https://cdn.dummyjson.com/product-images/98/4.jpg',
        'https://cdn.dummyjson.com/product-images/98/thumbnail.jpg',
      ],
      reviews: 757,
    },
    {
      id: 99,
      brand: 'Ifei Home',
      price: 46,
      stock: 138,
      title: 'American Vintage Wood Pendant Light',
      images: [
        'https://i.dummyjson.com/data/products/99/1.jpg',
        'https://i.dummyjson.com/data/products/99/2.jpg',
        'https://i.dummyjson.com/data/products/99/3.jpg',
        'https://i.dummyjson.com/data/products/99/4.jpg',
        'https://i.dummyjson.com/data/products/99/thumbnail.jpg',
      ],
      rating: 4.32,
      reviews: 86,
      category: 'lighting',
      thumbnail:
        'https://i.dummyjson.com/data/products/99/thumbnail.jpg',
      description:
        'American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante. SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with',
      discountPercentage: 8.84,
    },
    {
      id: 100,
      title: 'Crystal chandelier maria theresa for 12 light',
      description:
        "Crystal chandelier maria theresa for 12 light. Elevate the elegance of your living space with the YIOSI Crystal Chandelier. This maria theresa chandelier features 12 lights, creating a dazzling and luxurious ambiance. With a discount percentage of 16%, it's a statement piece for any room. Bring opulence to your home with this crystal chandelier and enjoy the timeless beauty it adds to your decor.",
      price: 47,
      discountPercentage: 16,
      rating: 4.74,
      stock: 133,
      brand: 'YIOSI',
      category: 'lighting',
      thumbnail:
        'https://cdn.dummyjson.com/product-images/100/thumbnail.jpg',
      images: [
        'https://cdn.dummyjson.com/product-images/100/1.jpg',
        'https://cdn.dummyjson.com/product-images/100/2.jpg',
        'https://cdn.dummyjson.com/product-images/100/3.jpg',
        'https://cdn.dummyjson.com/product-images/100/thumbnail.jpg',
      ],
      reviews: 757,
    },
  ],
  total: 100,
  skip: 0,
  limit: 100,
};
