import React from 'react';
import type { Metadata } from 'next';
import './styles/globals.css';
import ReactQueryProvider from '@/lib/providers/react-query.provider';
import { inter, poppins } from './font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} ${inter.variable}`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
